name: "Create Release"
description: "Create Github Release based on LoiLo Flow"
author: "LoiLo"
inputs:
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
  release_name:
    description: 'The name of the release. For example, `Release v1.0.1`'
    required: true
  draft:
    description: '`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`'
    required: false
    default: false
  prerelease:
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'lib/index.js'